.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/prlint.json

docs: Update issue templates

---

.storybook/preview-head.html
package.json
yarn.lock

Load custom fonts declared in the `@useblu/tokens` to render in the storybook app.

feat: Loads custom fonts in storybook

---

src/Input/Input.tsx
src/Input/__tests__/Input.test.tsx
src/Input/index.ts
src/Input/stories/Input.stories.mdx
src/Input/styles/input.scss
src/index.ts

_Package: `@useblu/ocean-components@0.1.0-beta.9`_
- https://material-ui.com/api/text-field/#props
- https://ant.design/components/input/#API

feat: Adds input component

---

src/Button/stories/Button.stories.mdx
src/Button/styles/button.scss

fix: button styles

---

.storybook/preview.js
src/Button/stories/Button.stories.mdx
src/Link/Link.tsx
src/Link/__tests__/Link.test.tsx
src/Link/index.ts
src/Link/stories/Link.stories.mdx
src/Link/styles/link.scss
src/index.ts

_Package: `@useblu/ocean-components@0.1.0-beta.15`_
- https://material-ui.com/api/link/

feat: Creates a Link component

---

package.json
src/FormControl/FormControl.tsx
src/FormControl/__tests__/FormControl.test.tsx
src/FormControl/index.ts
src/FormControl/stories/FormControl.stories.mdx
src/FormControl/styles/form-control.scss
src/Input/Input.tsx
src/Input/__tests__/Input.test.tsx
src/Input/stories/Input.stories.mdx
src/Input/styles/input.scss
src/TextArea/TextArea.tsx
src/TextArea/__tests__/TextArea.test.tsx
src/TextArea/stories/TextArea.stories.mdx
src/TextArea/styles/textarea.scss
yarn.lock

- https://material-ui.com/api/form-control/#formcontrol-api

feat: Adds FormControl component

---

.github/RELEASING.md

This PR creates a file of guidelines for releasing Ocean DS packages.

docs: include releasing guidelines

---

.github/CONTRIBUTING.md
README.md

Updates project documentation.

docs: update readme and contributing

---

packages/ocean-core/src/forms/_radio.scss
packages/ocean-core/src/forms/_switch.scss

__Change the color of the `Switch` input when it is not checked__
According to design team request, when the value is not checked on a `Switch` component its color should be dark-gray instead of red.
__Improve `Radio` input styles, removing pseudo-element `:after` and  making the border thicker__
Using `:after` to make the center of the input cause some strange behaviour in some situation. The element does not get aligned properly even though the margins were setted correctly.
Even trying to use `translate` to set the position make it misaligned.
To fix this, the pseudo-element was removed and the `span` component got a thicker border to make the same visual aspect.
The screenshots above were taken using Firefox.
To test if everything was ok, the inputs were rendered in 3 different …

Improve switch and radio

---

packages/ocean-core/src/components/_all.scss
packages/ocean-core/src/components/_modal.scss
packages/ocean-core/src/utils/_breakpoints.scss
packages/ocean-react/package.json
packages/ocean-react/src/Modal/Modal.tsx
packages/ocean-react/src/Modal/__tests__/Modal.test.tsx
packages/ocean-react/src/Modal/examples/SimpleModal.tsx
packages/ocean-react/src/Modal/index.ts
packages/ocean-react/src/Modal/stories/Modal.stories.mdx
packages/ocean-react/src/index.ts
yarn.lock

Implements ocean modal specified in our [Figma handoff](https://prnt.sc/12eo97a).
https://pagnet.github.io/ocean-ds-web/index.html?path=/story/components-modal--playground
https://user-images.githubusercontent.com/3240432/116831905-8af2c500-ab88-11eb-9a2d-96257211ade3.mp4

feat: add modal component

---

packages/ocean-core/src/components/_button.scss
packages/ocean-react/src/Button/Button.tsx
packages/ocean-react/src/Button/__tests__/Button.test.tsx
packages/ocean-react/src/Button/stories/Button.stories.mdx

Adds a critical variant to button component
Choosing the 'critical' variant (storybook)

feat(button): add critical variant

---

packages/ocean-core/src/components/_button.scss
packages/ocean-react/src/Button/Button.tsx
packages/ocean-react/src/Button/__tests__/Button.test.tsx
packages/ocean-react/src/Button/stories/Button.stories.mdx

Adds text button critical variant.
Fixes #739  
https://ocean-ds.github.io/ocean-web/?path=/story/components-button--playground&args=variant:textCritical
https://user-images.githubusercontent.com/3240432/129124196-e71d62a1-846e-4cf1-9ede-817367009dad.mp4

feat(button): add text-critical variant

---

packages/ocean-core/src/forms/_checkbox.scss

Updates checkbox border-width
Fixes #751 
https://ocean-ds.github.io/ocean-web/?path=/story/components-checkbox--playground

feat(checkbox): update border-width

---

packages/ocean-core/src/forms/_form-label.scss

Updates form label font styles
Fixes #752 
[FormLabel](https://ocean-ds.github.io/ocean-web/?path=/story/components-formlabel--usage), [Input](https://ocean-ds.github.io/ocean-web/?path=/story/components-input--playground), [Select](https://ocean-ds.github.io/ocean-web/?path=/story/components-select--playground), [TextArea](https://ocean-ds.github.io/ocean-web/?path=/story/components-textarea--playground)

feat(label): change font-weight from bold to regular

---

.storybook/preview.ts
packages/ocean-react/src/Grid/stories/Col.stories.mdx
packages/ocean-react/src/Grid/stories/Container.stories.mdx
packages/ocean-react/src/Grid/stories/Grid.stories.mdx
packages/ocean-react/src/Grid/stories/Row.stories.mdx
packages/ocean-react/src/Select/stories/Select.stories.mdx
packages/ocean-react/src/_stories/Examples.stories.mdx

Centers stories on cavas
Fixes #517 
https://ocean-ds.github.io/ocean-web
https://user-images.githubusercontent.com/3240432/129119190-9a678b32-9c78-48f3-8366-bf232860a4fb.mp4

docs(storybook): center story on canvas

---

packages/ocean-core/src/components/_all.scss
packages/ocean-core/src/components/_divider.scss
packages/ocean-react/src/Divider/Divider.tsx
packages/ocean-react/src/Divider/__tests__/Divider.test.tsx
packages/ocean-react/src/Divider/index.ts
packages/ocean-react/src/Divider/stories/Divider.stories.mdx
packages/ocean-react/src/index.ts

Creates a divider component.
Fixes #743 
http://localhost:6006/?path=/story/components-divider--usage&globals=backgrounds.value:!hex(393b47)
https://user-images.githubusercontent.com/3240432/129214280-409fee10-788a-4408-a54f-5c5863b4dbcb.mp4

feat: add divider component

---

packages/ocean-core/src/forms/_switch.scss

Adjustments on the switch component.
Fixes #771 
http://localhost:6006/?path=/story/components-switch--playground
https://user-images.githubusercontent.com/3240432/129251624-9da9bdcc-04a3-4612-afa9-307374e24acb.mp4

feat(switch): add hover state, update border and non-checked styles

---

.github/workflows/chromatic.yml
lerna.json
package.json
yarn.lock

Configurates screenshot test with chromatic.
Fixes #776

ci(chromatic): create workflow for screenshot test

---

packages/ocean-core/src/forms/_checkbox.scss
packages/ocean-react/src/Checkbox/Checkbox.tsx
packages/ocean-react/src/Checkbox/__tests__/Checkbox.test.tsx
packages/ocean-react/src/Checkbox/stories/Checkbox.stories.mdx

- Add Indeterminate state
- Change color tokens on Disabled states
Fixes #772 
http://localhost:6006/?path=/story/components-checkbox--playground&args=indeterminate:true
https://user-images.githubusercontent.com/3240432/129267016-fb184713-baf4-4689-862d-48a063790b09.mp4

feat(checkbox): add Indeterminate state and fix colors

---

packages/ocean-core/src/forms/_input.scss
packages/ocean-react/src/Input/Input.tsx
packages/ocean-react/src/Input/__tests__/Input.test.tsx
packages/ocean-react/src/Input/stories/Input.stories.mdx

feat(input): add input adornment

---

packages/ocean-core/src/components/_all.scss
packages/ocean-core/src/components/_tag.scss
packages/ocean-react/src/Tag/Tag.tsx
packages/ocean-react/src/Tag/TagIcon.tsx
packages/ocean-react/src/Tag/__tests__/Tag.test.tsx
packages/ocean-react/src/Tag/index.ts
packages/ocean-react/src/Tag/stories/Tag.stories.mdx

Adds a tag component that will be used in this [other]( https://github.com/ocean-ds/ocean-web/issues/740)

feat(tag): add tag component

---

package.json
yarn.lock

chore: bump immer to 9.0.6

---

packages/ocean-react/src/index.ts

fix(list): export list from module

---

packages/ocean-core/src/forms/_input.scss
packages/ocean-react/src/Input/Input.tsx
packages/ocean-react/src/Input/__tests__/Input.test.tsx
packages/ocean-react/src/Input/stories/Input.stories.mdx

Update the input behavior, making it accept a string instead of just being an icon.
Fixes #738 
Checking if there is a value already defined, if you don't have the string, it should have low opacity.

chore: adding currency input component

---

packages/ocean-react/src/Carousel/Carousel.tsx
packages/ocean-react/src/Carousel/__tests__/Carousel.test.tsx
packages/ocean-react/src/Carousel/stories/Carousel.stories.mdx

This PR aims to add some add an autoplay functionality on carousel component (default booelan parameter set to `false`)
Fixes #856 

fix: enabling autoplay on carousel (boolean)

---

packages/ocean-core/src/components/_all.scss
packages/ocean-core/src/components/_progress.scss
packages/ocean-core/src/components/_topbar.scss
packages/ocean-react/src/TopBar/TopBar.tsx
packages/ocean-react/src/TopBar/__tests__/TopBar.test.tsx
packages/ocean-react/src/TopBar/index.ts
packages/ocean-react/src/TopBar/stories/TopBar.stories.mdx
packages/ocean-react/src/index.ts

Created a top bar, displaying a magnifying glass and a back button, passing a function.
Fixes #747
Storybook, checking the [TopBar](https://ocean-ds.github.io/ocean-web/?path=/story/components-topbar--usage)

feat: new component topbar

---

packages/ocean-core/src/components/_topbar.scss
packages/ocean-react/src/TopBar/TopBar.tsx
packages/ocean-react/src/TopBar/__tests__/TopBar.test.tsx
packages/ocean-react/src/TopBar/stories/TopBar.stories.mdx

This pull request aims to make the top bar component more dynamic and customizable. The changes made to the component are:
- Dynamic title and subtitle props
- Dynamic left icon
- Spacing elements
Fixes #878
Storybook, checking the [TopBar](https://ocean-ds.github.io/ocean-web/?path=/story/components-topbar--usage)
And unity tests using Jest.

chore: update colors, variant and spacing

---

packages/ocean-core/src/components/_modal.scss

Adjust giving auto autura to scroll on mobile.

fix: scroll modal mobile

---

packages/ocean-core/src/components/_carousel.scss
packages/ocean-core/src/components/_topbar.scss
packages/ocean-react/src/TopBar/TopBar.tsx
packages/ocean-react/src/TopBar/__tests__/TopBar.test.tsx
packages/ocean-react/src/TopBar/stories/TopBar.stories.mdx

Fixes #
Issues with topbar. 
Issues with banner.

chore: fix topbar

---

packages/ocean-core/src/components/_all.scss
packages/ocean-core/src/components/_badge.scss
packages/ocean-react/src/Badge/Badge.tsx
packages/ocean-react/src/Badge/__tests__/Badge.test.tsx
packages/ocean-react/src/Badge/index.ts
packages/ocean-react/src/Badge/stories/Badge.stories.mdx
packages/ocean-react/src/Carousel/Carousel.tsx
packages/ocean-react/src/Carousel/__tests__/BannerExamples.test.tsx
packages/ocean-react/src/Carousel/__tests__/Carousel.test.tsx
packages/ocean-react/src/Carousel/examples/BannerExample.tsx
packages/ocean-react/src/Carousel/stories/Carousel.stories.mdx

feat(badge): add new badge component.

---

packages/ocean-core/src/components/_icon-button.scss
packages/ocean-react/src/IconButton/stories/IconButton.stories.mdx

fix(button): add hover transition to icon button variant.

---

packages/ocean-react/src/index.ts

Reverts ocean-ds/ocean-web#924

Revert "hotfix(badge): export default badge component."

---

yarn.lock

chore: upgrade libs

---

package.json
yarn.lock

fix(sec): Inefficient Regular Expression Complexity in chalk/ansi-regex

---

packages/ocean-core/src/forms/_textarea.scss

fix(textarea): add width 100% to textarea

---

packages/ocean-react/src/Tooltip/stories/Tooltip.stories.mdx

feat(tooltip): remove disable from control

---

packages/ocean-react/src/Steps/Steps.tsx
packages/ocean-react/src/Steps/stories/Stepper.stories.mdx

Refactor steps component to accept any length.
Test if steps components accept any length, if different values.
- [n] I have added tests that prove my fix is effective or that my feature works

Refactor steps component to accept any length

---

packages/ocean-core/src/forms/_checkbox.scss

- Add min-width and min-height to prevent checkbox change your size
- Change width and height to 20x20. Issue #951
Screenshot showing error

fix(checkbox): add min-width and min-height to checkbox

---

packages/ocean-core/src/forms/_checkbox.scss

Fix checkmark position. 
After:
Before:

fix(checkbox): fix checkmark position

---

packages/ocean-core/src/forms/_radio.scss
packages/ocean-core/src/forms/_switch.scss
packages/ocean-react/src/Checkbox/Checkbox.tsx
packages/ocean-react/src/Radio/Radio.tsx

This PR aims to update and adjust some little styles from the Checkbox, Switch, Radio button and Link components from the referred Issues. 
* width: 40px
* height: 20px
* selector (circle): 14x14
* padding: 2px

Fix: new dimensions to the switch component

---

packages/ocean-react/package.json
yarn.lock

This PR includes lodash types to the ocean-web package.

fix: add lodash types to the project

---

packages/ocean-core/src/components/_badge.scss
packages/ocean-core/src/components/_link.scss
packages/ocean-core/src/components/_typography.scss
packages/ocean-core/src/forms/_form-control.scss
packages/ocean-react/src/Divider/__tests__/Divider.test.tsx
packages/ocean-react/src/FileUploader/__tests__/FileUpload.test.tsx
packages/ocean-react/src/FormControl/FormControl.tsx
packages/ocean-react/src/FormControl/__tests__/FormControl.test.tsx
packages/ocean-react/src/FormControl/stories/FormControl.stories.mdx
packages/ocean-react/src/Input/Input.tsx
packages/ocean-react/src/Input/__tests__/Input.test.tsx
packages/ocean-react/src/Input/stories/0-Introduction.stories.mdx
packages/ocean-react/src/Input/stories/WithLabelIconTooltip.stories.mdx
packages/ocean-react/src/Link/Link.tsx
packages/ocean-react/src/Link/LinkIcons.tsx
packages/ocean-react/src/Link/__tests__/Link.test.tsx
packages/ocean-react/src/Link/__tests__/LinkIcons.test.tsx
packages/ocean-react/src/Link/stories/Link.stories.mdx
packages/ocean-react/src/Search/__tests__/Search.test.tsx
packages/ocean-react/src/Select/__tests__/Select.test.tsx
packages/ocean-react/src/Stepper/__tests__/Stepper.test.tsx
packages/ocean-react/src/TextArea/__tests__/TextArea.test.tsx
packages/ocean-react/src/Typography/Typography.tsx
packages/ocean-react/src/Typography/stories/Typography.stories.mdx

This PR fixes some component issues that were open and needed to be resolved. Those issues are: 
*  [Add Tooltip option on Inputs](https://github.com/ocean-ds/ocean-web/issues/901)
* [New typography component - Heading 5 (Web)](https://github.com/ocean-ds/ocean-web/issues/999)
* [Remove shadow from Badge / Text variation (Web)](https://github.com/ocean-ds/ocean-web/issues/976)
* [New variations for Link component (Web)](https://github.com/ocean-ds/ocean-web/issues/820)
This has been tested by unit tests and Storybook.

feat: components adjustments

---

packages/ocean-core/src/components/_date-picker.scss
packages/ocean-react/src/DatePicker/DatePicker.tsx
packages/ocean-react/src/DatePicker/__tests__/DatePicker.test.tsx

This PR fixes some layout bugs and prevents global overwrites.

fix: datepicker

---

packages/ocean-core/src/components/_link.scss

fix: component link with icons

---

packages/ocean-react/src/Search/Search.tsx

This PR fix the update of Search component when receive onChange prop.
Fixes #1043
Try to use Search component passing onChange prop

fix: pass input value attribute

---

packages/ocean-core/src/forms/_input.scss
yarn.lock

Remove margin on input__adornment to fix input

fix: remove input margin

---

packages/ocean-core/src/components/_all.scss
packages/ocean-core/src/components/breadcrumb.scss
packages/ocean-react/src/Breadcrumb/Breadcrumb.tsx
packages/ocean-react/src/Breadcrumb/__tests__/Breadcrumb.test.tsx
packages/ocean-react/src/Breadcrumb/index.ts
packages/ocean-react/src/Breadcrumb/stories/Breadcrumb.stories.mdx
packages/ocean-react/src/index.ts

New component breadcrumb to initial page.

feat: add component breadcrumb

---

packages/ocean-react/src/Date/__tests__/DatePicker.test.tsx

This PR fix date-picker component tests.

fix: adjust DatePicker test

---

packages/ocean-core/src/forms/_checkbox.scss
packages/ocean-react/src/Checkbox/stories/Checkbox.stories.mdx

this PR fix position  in component checkbox in scrolling navigation.

fix: position component checkbox

---

packages/ocean-core/src/components/_cross-sell-card.scss
packages/ocean-react/src/CrossSellCard/CrossSellCard.tsx
packages/ocean-react/src/CrossSellCard/__tests__/CrossSellCard.tsx

Fix titles and sizes image in component cross sell card.

fix: title cross sell card

---

packages/ocean-core/src/components/_cross-sell-card.scss

Hotfix description in component cross sell card.

fix: sizes description cross sell card

---

.husky/pre-commit
packages/ocean-core/src/components/_all.scss
packages/ocean-core/src/components/_snackbar.scss
packages/ocean-react/src/Snackbar/Snackbar.tsx
packages/ocean-react/src/Snackbar/__tests__/Snackbar.test.tsx
packages/ocean-react/src/Snackbar/hook/useSnackbar.ts
packages/ocean-react/src/Snackbar/index.ts
packages/ocean-react/src/Snackbar/stories/Snackbar.stories.mdx
packages/ocean-react/src/index.ts

This PR add Snackbar component.
Run this branch in localhost to see the Snackbar component.
Type info
Type warning
Type success
Type error

feat: snackbar component

---

packages/ocean-core/src/components/_all.scss
packages/ocean-core/src/components/_shortcut.scss
packages/ocean-react/src/Badge/Badge.tsx
packages/ocean-react/src/Shortcut/Shortcut.tsx
packages/ocean-react/src/Shortcut/__tests__/Shortcut.spec.tsx
packages/ocean-react/src/Shortcut/index.ts
packages/ocean-react/src/Shortcut/stories/Shortcut.stories.mdx
packages/ocean-react/src/index.ts

This pull request adds the Shortcut component to our design system.
Open storybook and test in shotcut tab.

feat: create shortcut component

---

packages/ocean-react/src/Drawer/Drawer.tsx
packages/ocean-react/src/Drawer/stories/Drawer.stories.mdx

Add mouse event dispatach inside drawer.

feat: add mouse events on drawer

---

packages/ocean-react/src/Drawer/Drawer.tsx

fix: adjust data-tesid tag name

---

packages/ocean-core/src/components/_shortcut.scss
packages/ocean-react/src/Shortcut/Shortcut.tsx
packages/ocean-react/src/Shortcut/__tests__/Shortcut.spec.tsx
packages/ocean-react/src/Shortcut/stories/Shortcut.stories.mdx

Add orientation and full width on shortcut, and remove large size.
Open storybook and check new props.

feat: add orientation prop on shortcut

---

packages/ocean-core/src/forms/_checkbox.scss

fix: Center checkbox icon

---

packages/ocean-core/src/components/_search.scss
packages/ocean-core/src/forms/_input.scss
packages/ocean-core/src/forms/_textarea.scss
packages/ocean-react/src/Date/__tests__/DatePicker.test.tsx
packages/ocean-react/src/Date/__tests__/DateRange.test.tsx
packages/ocean-react/src/FileUploader/__tests__/FileUpload.test.tsx
packages/ocean-react/src/FormControl/FormControl.tsx
packages/ocean-react/src/FormControl/__tests__/FormControl.test.tsx
packages/ocean-react/src/Input/__tests__/Input.test.tsx
packages/ocean-react/src/Search/__tests__/Search.test.tsx
packages/ocean-react/src/TextArea/__tests__/TextArea.test.tsx

Remove margem desnecessárioa que fazia o input "dançar" no hover ou no foco e adiciona condição para renderizar div. 

feat: remove unused margin an add condicional render in input label

---

packages/ocean-core/src/components/breadcrumb.scss
packages/ocean-react/src/Breadcrumb/Breadcrumb.tsx
packages/ocean-react/src/Breadcrumb/__tests__/Breadcrumb.test.tsx

Ajuste de alinhamento do chevron

feat: center chevron with content

---

packages/ocean-core/src/components/_list-item.scss
packages/ocean-core/src/components/breadcrumb.scss
packages/ocean-core/src/utils/_all.scss
packages/ocean-core/src/utils/line-clamp.scss

Adjust list tex color and size and.
Adjust colum gap size in list container.
The tests were conducted using Storybook, and there were minor changes to colors and font sizes.

feat: adjust color and font size list

---

packages/ocean-core/src/components/_button.scss
packages/ocean-react/src/Button/Button.tsx
packages/ocean-react/src/Button/stories/Button.stories.mdx

feat: create button variants

---

packages/ocean-core/src/components/breadcrumb.scss

This PR add padding in breadcrumb.

fix: add padding breadcumb

---

packages/ocean-core/src/components/_all.scss
packages/ocean-core/src/components/_chips.scss
packages/ocean-react/src/Chips/Chips.tsx
packages/ocean-react/src/Chips/Options.tsx
packages/ocean-react/src/Chips/__tests__/Chips.test.tsx
packages/ocean-react/src/Chips/index.ts
packages/ocean-react/src/Chips/stories/Chips.stories.mdx
packages/ocean-react/src/index.ts

feat: create chips component

---

packages/ocean-core/src/components/_chips.scss
packages/ocean-react/src/Chips/Chips.tsx
packages/ocean-react/src/Chips/Options.tsx
packages/ocean-react/src/Chips/__tests__/Chips.test.tsx
packages/ocean-react/src/Chips/stories/Chips.stories.mdx

implement selected value at chips

feat: selected value at chips

---

packages/ocean-react/src/Chips/Chips.tsx
packages/ocean-react/src/Chips/__tests__/Chips.test.tsx

Activated selectOption prop when is multi select

feat(chips): select option to multi choice

---

packages/ocean-core/package.json
yarn.lock

chore: update tokens version

---

packages/ocean-core/src/components/_alert.scss
packages/ocean-core/src/components/_snackbar.scss
packages/ocean-react/src/Alert/Alert.tsx
packages/ocean-react/src/Alert/__tests__/Alert.test.tsx
packages/ocean-react/src/Alert/stories/Alert.stories.mdx

Add button on alert and add size variant.
[Figma Documentation](https://www.figma.com/file/PgLv9k22CHHZZ867HwN65y/%F0%9F%8C%8A-Ocean-DS-Core?type=design&node-id=13477-4225&mode=dev) - [Zero height](https://zeroheight.com/9c9b2b3aa/p/288747-alert/b/8846e5)

feat: alert button

---

packages/ocean-core/src/components/_list-item.scss
packages/ocean-react/src/TransactionListItem/TransactionListItem.tsx
packages/ocean-react/src/TransactionListItem/stories/TransactionListItem.stories.mdx

Adjusts on transaction list item

fix: adjust on transaction list item

---

packages/ocean-core/src/components/_alert.scss

fix: adjust alert content

---

packages/ocean-core/src/components/_drawer.scss
packages/ocean-react/src/Drawer/Drawer.tsx
packages/ocean-react/src/Drawer/__tests__/Drawer.test.tsx
packages/ocean-react/src/Drawer/examples/AttachedDrawer.tsx
packages/ocean-react/src/Drawer/examples/SimpleDrawer.tsx
packages/ocean-react/src/Drawer/stories/Drawer.stories.mdx

Add a drawer size varian: sizes "small" or "large"

feat: drawer

---

packages/ocean-core/src/components/_accordion.scss
packages/ocean-core/src/components/_unordered-list.scss

Add padding in unordered list component

chore: unordered list padding

---

packages/ocean-core/package.json
packages/ocean-core/src/components/_typography.scss
packages/ocean-core/src/components/breadcrumb.scss
packages/ocean-react/src/Typography/Typography.tsx
packages/ocean-react/src/Typography/stories/Typography.stories.mdx
yarn.lock

Updates typography component with new styles.

feat: update typography

---

packages/ocean-core/src/components/_all.scss
packages/ocean-core/src/components/_web-notification.scss
packages/ocean-react/src/WebNotification/WebNotification.tsx
packages/ocean-react/src/WebNotification/__tests__/WebNotification.test.tsx
packages/ocean-react/src/WebNotification/__tests__/__snapshots__/WebNotification.test.tsx.snap
packages/ocean-react/src/WebNotification/hook/useWebNotification.ts
packages/ocean-react/src/WebNotification/index.ts
packages/ocean-react/src/WebNotification/stories/WebNotification.stories.mdx
packages/ocean-react/src/index.ts

Add a new component webnotification

feat: create web notification component

---

packages/ocean-core/src/components/_web-notification.scss

Fixes web notification component

fix: web notification style

---

packages/ocean-react/src/Date/DatePicker.tsx
packages/ocean-react/src/Date/DateRange.tsx

Fix date components to show helper texts when receive props.

fix: adjust bug when show helper text in date components

---

packages/ocean-react/src/Chips/Chips.tsx
packages/ocean-react/src/Chips/__tests__/Chips.test.tsx

include events for buttons when multichoice

feat: include events for buttons when multichoice

---

packages/ocean-react/package.json

fix: remove peer dependency

---

.github/workflows/cd.yml
.github/workflows/chromatic.yml
.github/workflows/ci.yml
.github/workflows/site.yml

Upgrade actions/cache@v2 from workflows to actions/cache@v4.

ci: upgrade actions cache version

---

package.json
scripts/generate-sitemap.js

Reverts ocean-ds/ocean-web#1150

feat: adjust sitemap

---

packages/ocean-core/src/components/_shortcut.scss

fix: adjust line-height in Shortcut component styles for improved layout

---

.github/workflows/deploy-docs.yml
packages/ocean-docs/docusaurus.config.ts

chore: refactor deployment workflow for documentation and Storybook
