ocean-ds/ocean-web

.vscode/extensions.json
src/Grid/Col.tsx
src/Grid/Container.tsx
src/Grid/Row.tsx
src/Grid/__tests__/Col.test.tsx
src/Grid/__tests__/Container.test.tsx
src/Grid/__tests__/Row.test.tsx
src/Grid/index.ts
src/Grid/stories/Col.stories.mdx
src/Grid/stories/Container.stories.mdx
src/Grid/stories/Grid.stories.mdx
src/Grid/stories/Row.stories.mdx
src/Grid/styles/_breakpoints.scss
src/Grid/styles/_functions.scss
src/Grid/styles/_grid.scss
src/Grid/styles/_variables.scss
src/Grid/styles/col.scss
src/Grid/styles/container.scss
src/Grid/styles/row.scss
src/Grid/styles/stories.scss
src/Typography/Typography.tsx
src/Typography/__tests__/Typography.test.tsx
src/Typography/stories/Typography.stories.mdx
src/index.ts

_Package: `@useblu/ocean-components@0.1.0-beta.4`_
- https://material-ui.com/api/grid/
- https://getbootstrap.com/docs/4.5/layout/grid/
- https://react-bootstrap.github.io/layout/grid/

feat: Include grid-system components

---

src/Typography/Typography.tsx
src/Typography/stories/Typography.stories.mdx
src/Typography/styles/typography.scss

_Package: `@useblu/ocean-components@0.1.0-beta.19`_
```js
import React from 'react';
import { Typography } from '@useblu/ocean-components';
const ExempleTypography = () => {
return (
<div className='page'>
<Typography variant="lead">Hello</Typography>
<Typography variant="caption">Hello</Typography>
</div>
)
}
export default ExempleTypography;
```
Link to storybook: 
- https://pagnet.github.io/ocean-ds-web/index.html?path=/docs/components-typography--usage#typography-api

typography caption and lead

---

src/FormControl/FormControl.tsx
src/FormControl/__tests__/FormControl.test.tsx
src/FormControl/stories/FormControl.stories.mdx
src/FormControl/styles/form-control.scss
src/Input/Input.tsx
src/TextArea/TextArea.tsx

Fix the label and helper text in the disabled state.

fix: form control disabled states

---

README.md

Fix wrong location of ocean-ds.min.css in the README file.
No new tests. Only doc update

docs(readme): adjust ocean-ds.min.css path

---

packages/ocean-core/src/forms/_checkbox.scss
packages/ocean-core/src/forms/_radio.scss
packages/ocean-core/src/forms/_switch.scss

This change was been suggested by user feedback, the old color has
creating confusion cause it was like a canceled or not ok state.
Its only a color change, no need for multiple browser tests.

fix: change color from switch, radio and checkbox.

---

packages/ocean-core/src/components/_link.scss
packages/ocean-react/src/Link/Link.tsx
packages/ocean-react/src/Link/__tests__/Link.test.tsx
packages/ocean-react/src/Link/stories/Link.stories.mdx

Includes a size prop in the Link component.
Fixes #760 
https://ocean-ds.github.io/ocean-web/?path=/story/components-link--playground

feat(link): include size property

---

packages/ocean-core/src/components/_alert.scss
packages/ocean-core/src/components/_all.scss
packages/ocean-react/src/Alert/Alert.tsx
packages/ocean-react/src/Alert/AlertIcon.tsx
packages/ocean-react/src/Alert/__tests__/Alert.test.tsx
packages/ocean-react/src/Alert/index.ts
packages/ocean-react/src/Alert/stories/Alert.stories.mdx
packages/ocean-react/src/index.ts

This adds a new Alert component, with all variations as shown in the [hand-off ](https://www.figma.com/file/PgLv9k22CHHZZ867HwN65y/%E2%9D%96-Ocean-DS-%2F-Core-Components?node-id=2856%3A23387) doc, plus a way to custom set an icon in the component.

feat: add alert component

---

packages/ocean-react/src/Alert/Alert.tsx
packages/ocean-react/src/Alert/AlertIcon.tsx
packages/ocean-react/src/Alert/__tests__/Alert.test.tsx
packages/ocean-react/src/Alert/stories/Alert.stories.mdx

Adds a wrapper to the alert content, to let user to have a alert with how many children they want. 
without the fix
with the fix

fix(alert): adds a wrapper for content

---

packages/ocean-core/src/forms/_select.scss

Adding a z-index css property to the select stylesheet page to fix the double select issue.

fix: double select z-index problem

---

packages/ocean-react/src/Badge/Badge.tsx
packages/ocean-react/src/Badge/__tests__/Badge.test.tsx
packages/ocean-react/src/Badge/stories/Badge.stories.mdx

Fixes the badge component when count prop is zero.
Due to 0 being interpreted as a falsy value it made the condition where the badge styles were applied simply got ignored.
Since `count` can only be `number | undefined` I chose to strictly check if its not `undefined`.
Also added a test specifically checking if the badge with `count={0}` matches the snapshot of a expected dom node.
[CB-1350](https://useblu.atlassian.net/jira/software/c/projects/CB/boards/106?modal=detail&selectedIssue=CB-1350)
https://ocean-ds.github.io/ocean-web/?path=/story/components-badge--count
or locally:
http://localhost:6006/?path=/story/components-badge--count

fix(badge): fixes badge not being displayed properly on count=0

---

.github/workflows/codeql-analysis.yml
.github/workflows/semantic.yml
packages/ocean-core/src/components/_cross-sell-card.scss
packages/ocean-react/src/CrossSellCard/CrossSellCard.tsx
packages/ocean-react/src/CrossSellCard/__tests__/CrossSellCard.tsx
packages/ocean-react/src/FormLabel/FormLabel.tsx
packages/ocean-react/src/FormLabel/__tests__/FormLabel.test.tsx
packages/ocean-react/src/Grid/__tests__/Col.test.tsx
packages/ocean-react/src/Grid/__tests__/Row.test.tsx
packages/ocean-react/src/IconButton/IconButton.tsx
packages/ocean-react/src/Select/Option.tsx

makes the whole component clickable, executing the ctaAction function passed as prop
Adds a custom icon prop to the component, a JSX.Element can be passed and it will appear near the bottom right where the button icon is. Falls back to the ChevronRight icon which was already used by default.
CrossSellCard component needed an increased clickable area. Added a onClick on the div and fixed an issue that prevent the ctaAction from being fired twice.
https://ocean-ds.github.io/ocean-web/?path=/story/components-crosssellcard--usage
or locally:
http://localhost:6006/?path=/story/components-crosssellcard--usage

feat(crosssellcard): CustomIcon + increases the clickable area for the whole component 

---

packages/ocean-core/src/components/_sub-header.scss

Adjust sub header padding and min height, according this issue https://github.com/ocean-ds/ocean-web/issues/1049

fix: adjust sub header padding and height

---

packages/ocean-core/src/forms/_form-control.scss

This PR fixes the input label margin-bottom 

fix: adds a 8px margin to the input component label

---

packages/ocean-core/src/components/_drawer.scss
packages/ocean-react/src/Drawer/Drawer.tsx
packages/ocean-react/src/Drawer/__tests__/Drawer.test.tsx
packages/ocean-react/src/Drawer/examples/AttachedDrawer.tsx
packages/ocean-react/src/Drawer/examples/SimpleDrawer.tsx
packages/ocean-react/src/Drawer/stories/Drawer.stories.mdx

Add align property to the drawer component to enable alignment on both the left and right sides.
Create an attach mode for the drawer component, allowing it to open on the side of another element, either on the right or left.
Open drawer passing align and anchorEl, in props.

feat: add attach mode to drawer

---

packages/ocean-react/src/Drawer/Drawer.tsx
packages/ocean-react/src/Drawer/__tests__/Drawer.test.tsx
packages/ocean-react/src/Shortcut/Shortcut.tsx

Adjust overlay click on drawer, to only close when de overlay is clicked, not a child.
Add div behavior to shortcut

fix: adjust handle clicks on drawer and shortcut

---

packages/ocean-core/src/components/breadcrumb.scss
packages/ocean-react/src/Breadcrumb/Breadcrumb.tsx
packages/ocean-react/src/Breadcrumb/__tests__/Breadcrumb.test.tsx
packages/ocean-react/src/Breadcrumb/stories/Breadcrumb.stories.mdx

Adiciona a key prop na renderização do map no componente breadcrumb

fix: breadcrumb map key prop

---

packages/ocean-core/src/forms/_input.scss

Add a transparent border on input when is not active to stop "jumping".
Hover or put in focus the input
Before: https://ocean-ds.github.io/ocean-web/?path=/story/components-inputs-text--text
After: https://6115c6277dff2e003c1d0e2d-aquzhpbmkr.chromatic.com/?path=/story/components-inputs-text--text

fix: remove input jump on hover

---

packages/ocean-core/src/components/breadcrumb.scss
packages/ocean-react/src/Date/DateHeader.tsx
packages/ocean-react/src/Date/DatePicker.tsx
packages/ocean-react/src/Date/DateRange.tsx
packages/ocean-react/src/Date/hooks/useDatePicker.ts
packages/ocean-react/src/Date/hooks/useDateRange.ts
packages/ocean-react/src/Date/types/DatePicker.types.ts
packages/ocean-react/src/Date/types/DateRange.types.ts

When a user selects a date and clicks back into the field, the month shown on the calendar is not the one that was selected
In Storybook, select DateRange or Datepicker, choose a date, and click on the input again; the month shown on the calendar should be the one corresponding to the selected date.
Before fix
After
https://github.com/ocean-ds/ocean-web/assets/102989712/b70a683e-6742-4a1e-be06-3800e7c3752c

fix: adjusts on Date component

---

packages/ocean-core/src/components/_chips.scss
packages/ocean-react/src/Chips/Chips.tsx
packages/ocean-react/src/Chips/Options.tsx
packages/ocean-react/src/Chips/__tests__/Chips.test.tsx
packages/ocean-react/src/Chips/stories/Chips.stories.mdx

Create multi options to chips component

feat: add multi choice options on chips

---

.github/workflows/chromatic.yml
packages/ocean-core/src/components/_list-item.scss
packages/ocean-react/src/TransactionListItem/TransactionListItem.tsx
packages/ocean-react/src/TransactionListItem/__tests__/TransactionListItem.test.tsx

This PR fixes the transaction list item padding and changes the chromatic action to v11.4.0 due to an error in the latest version
error reported on:
github.com/chromaui/chromatic-cli/issues/1000

fix: transaction list item

---

packages/ocean-core/src/components/_typography.scss
packages/ocean-core/src/components/breadcrumb.scss

adjust in typography and bradvrumbs

fix: adjust breadcrumb and typography

---

packages/ocean-core/src/components/_card-list-item.scss
packages/ocean-react/src/CardListItem/CardListItem.tsx
packages/ocean-react/src/CardListItem/__tests__/CardListItem.test.tsx
packages/ocean-react/src/CardListItem/stories/CardListItem.stories.mdx

Updates Card Lis Item component styles and documentation. 

feat: update card list item component

---

packages/ocean-core/src/components/_shortcut.scss
packages/ocean-docs/docs/components/shortcut.mdx
packages/ocean-react/src/Shortcut/Shortcut.tsx
packages/ocean-react/src/Shortcut/stories/Shortcut.stories.tsx

This PR ajusts tag position and a limitation to permit only tag or count prop.
Just render Shortcut component and try to pass count and tag props.

fix: tag position and limit props to accept only tag or count prop
